### ISSUE TITLE
Change notebook links to point to correct version

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib-docs#10]
Currently we have hyperlinks in the notebooks pointing to the `latest` compiled wradlib documentation. For the notebooks (in [wradlib-notebooks](https://github.com/wradlib/wradlib-notebooks)) this is probably the best solution always pointing to the latest available compiled docs. 

For the docs itself it is somewhat counterintuitive if you link from the `stable` version to `latest`. The suggestion would be to identify these links (they all begin with `https://docs.wradlib.org/en/latest/`) and correct them to the needed version. This can be done within `conf.py` where the correct version is already identified.

Thoughts?

**Comment by heistermann** [comment]
Sounds very reasonable.

**Comment by kmuehlbauer** [comment]
resolved by #11
