### ISSUE TITLE
Add section of wradlib usage

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib-docs#16]
- in organizations
- in projects
- in papers etc.
- etc.

**Comment by GolGosh** [comment]
I work on research project regarding weather radar statistics. 
I use WRADLIB for radar data processing.

**Comment by kmuehlbauer** [comment]
@GolGosh Thanks for sharing. We would add your research project to a list in the documentation. So a short summary of the project and information on how to cite project would be very nice?
